# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DgKq0mpVwPVWMCyb9Vz-d7YQXjw5FXo1
"""

import random

def generate_question():
    num1 = random.randint(1, 10)
    num2 = random.randint(1, 10)
    return num1, num2

def check_answer(num1, num2, user_answer):
    correct_answer = num1 + num2
    return user_answer == correct_answer

def play_game():
    score = 0
    num_questions = 5

    for _ in range(num_questions):
        num1, num2 = generate_question()
        question = f"What is {num1} + {num2}? "
        user_answer = int(input(question))

        if check_answer(num1, num2, user_answer):
            print("Correct!")
            score += 1
        else:
            print("Incorrect!")

    print(f"Game Over! Your score is {score}/{num_questions}")

play_game()